name: Release Rust Crate

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      version:
        description: The version to build

jobs:
  release:
    permissions:
      id-token: write

    runs-on: ubuntu-latest
    environment: release
    steps:
      - uses: actions/checkout@v5
        with:
          # The tag to build or the tag received by the tag event
          ref: ${{ github.event.inputs.version || github.ref }}
          persist-credentials: false

      - uses: rust-lang/crates-io-auth-action@v1
        id: auth

      - name: Publish to crates.io
        run: cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}
